name: CI for React

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif

      - name: List directory contents
        run: ls -la

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: my-analysis-tool
        
      - name: Print Snyk report
        run: cat snyk.sarif      

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
